"""Pydantic schemas for structured LLM input/output."""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class ActionType(str, enum.Enum):
    """Available browser actions the LLM can request."""

    NAVIGATE = "navigate"
    CLICK = "click"
    TYPE = "type"
    SCROLL = "scroll"
    SELECT = "select"
    EXTRACT = "extract"
    WAIT = "wait"
    PRESS = "press"
    DONE = "done"


class PlanSchema(BaseModel):
    """Task plan generated by the planner LLM call."""

    goal: str = Field(description="The user's goal restated clearly")
    steps_estimate: int = Field(description="Estimated number of browser steps")
    first_url: str = Field(description="Starting URL for browser navigation")
    plan_summary: str = Field(description="Brief summary of the approach")


class ActionSchema(BaseModel):
    """Single action decided by the executor LLM call."""

    action: ActionType = Field(description="The type of browser action to perform")
    target: str | None = Field(default=None, description="CSS selector or URL target")
    value: str | None = Field(default=None, description="Value to type, option to select, etc.")
    reasoning: str = Field(default="", description="Why this action was chosen")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="Confidence in this action")
    data: list[dict[str, Any]] | None = Field(
        default=None,
        description="Extracted data (only when action=done or action=extract)",
    )


class ObservationSchema(BaseModel):
    """Snapshot of the current page state sent to the LLM."""

    url: str = Field(description="Current page URL")
    title: str = Field(description="Current page title")
    dom_text: str = Field(description="Simplified DOM content — visible text and interactable elements")
    screenshot_b64: str | None = Field(default=None, description="Base64-encoded screenshot PNG")
    timestamp: datetime = Field(default_factory=datetime.now)


class StepRecord(BaseModel):
    """Record of a single step in the execution loop."""

    step_number: int
    observation: ObservationSchema
    action: ActionSchema
    success: bool = True
    error: str | None = None


class RunResultSchema(BaseModel):
    """Final result of a completed agent run."""

    run_id: str
    task: str
    plan: PlanSchema
    steps: list[StepRecord] = Field(default_factory=list)
    data: list[dict[str, Any]] = Field(default_factory=list)
    total_steps: int = 0
    elapsed_seconds: float = 0.0
    status: str = "completed"  # completed | failed | max_steps_reached
    started_at: datetime = Field(default_factory=datetime.now)
    finished_at: datetime | None = None
